### ISSUE TITLE
in contexts, adding an image uses absolute path

### ISSUE THREAD

**Issue by sdoney** [splittingred/TinyMCE#11]
in web context, adding an image uses relative path [/assets/images/image.jpg]

in blog context, adding an image uses absolute path [/var/www/blog.domain.com/assets/images/image.jpg] 

(image preview is also broken but i think this is a byproduct of it bringint the absolute path to the image preview)

the behavior in the blog context should match that of the web context

**Comment by wshawn** [comment]
This could be a simple issue of how the sub domain was created.  There are three ways I have seen it done: as a complete new domain, as a directory equal to the main docs directory and as a sub folder within the main directory (i.e. domain.com/bl0g = blog.domain.com).

I believe, you have to adjust the settings for your context to match the actual asset path you are planning on using.

**Comment by sdoney** [comment]
i have done that, i have a 'blog' context setting 

filemanager_path = /var/www/blog.domain.com/assets/

its loading the directory up in the file browser, but returning the absolute path of the image chosen

**Comment by splittingred** [comment]
This was fixed in Revo 2.0.5
