### ISSUE TITLE
While creating multilevel bulleted/numbered list, HTML DOM temporarily corrupted

### ISSUE THREAD

**Issue by juro** [splittingred/TinyMCE#13]
When selecting one or more lines in bulleted/numbered list and pressing indent to create 2nd (3rd etc.) level, HTML strucure gets incorrect on that lines:
<ul><li><li>
should be:
<ul><li><ul><li>
The same with ol/li tags. It gets corrected on next cleanup but until then this confuses users because page get rendered incorrectly. Workaround is to create additional CSS rules using syntax li>li rules.

**Comment by splittingred** [comment]
Seems to be fixed in TinyMCE upgrade to 4.2.4; will be in next TinyMCE release.
