### ISSUE TITLE
Text not wrapping and adding line breaks in TinyMCE for Revo (2.0.2)

### ISSUE THREAD

**Issue by brianlarson** [splittingred/TinyMCE#15]
See attached screenshot and note the hugegantic horizontal scrollbar. It's also adding double the typical spacing between paragraphs (<p>nbsp;</p> or break elements are not between them in the code). I also saw this in RC2.

Screenshot link: http://j.mp/dv1lgP

**Comment by splittingred** [comment]
I can't seem to replicate this at all. Try uninstalling and reinstalling TinyMCE.

**Comment by brianlarson** [comment]
Sorry it took so long to reply. Now I can't recreate the problem either and I've done nothing. Sorry for the wild goose chase here—hopefully it fixed itself and is gone forever. Thanks for taking a look though, splittingred! I'll let you know if it happens again if I have any idea of what may have triggered it.

**Comment by Marcelli** [comment]
I am having the same issue as brianlarson. Can't seem to understand how it appeared. To me it came up entirely unexpectedly, the only change I made was to remove advimage from the plugin list. Then I added it back just in case, but tinyMCE still refuses to wrap the text in the editor. I can't reproduce it, but it is here, very, very annoying: the horizontal scroll bar is broad as hell. In Chrome and FireFox, using Revo 2.2.4.

**Comment by Marcelli** [comment]
I have just reinstalled tinyMCE, to no avail. Please, help!
Splittingred, looking at the html of the editor, here is what I see within the tinyMCE Iframe:

``` html
<body id="tinymce" class="mceContentBody " onload="window.parent.tinyMCE.get('ta').onLoad.dispatch();" contenteditable="true" spellcheck="false" dir="ltr" style="white-space: nowrap; ">...</body>
```

JS adds "nowrap" here for some reason that I don't get. However, in the system settings, 'tiny.nowrap' is set to 'no', I have never changed this setting.
Can you explain me what is the setting I should change to get "white-space: normal" (apart from modifying the stylesheet)? Thanks a lot in advance!
