### ISSUE TITLE
Only english language work in Modxlink plugin.

### ISSUE THREAD

**Issue by Paprikas** [splittingred/TinyMCE#16]
Modx 2.0.4 pl2
TinyMce 4.1.1
screen
http://dl.dropbox.com/u/1187654/MODx/tinylanguage.png

Other users have same experience.

**Comment by Paprikas** [comment]
Same behavior with 2.0.1

**Comment by MadeMyDay** [comment]
Same problem here (german).
Other plugins work (image etc.). Even renaming de_dlg.js to en_dlg.js does not help, same error. The lang file is not found or (for not standard languages) not correctly called.

**Comment by enigmatic-user** [comment]
I'm not absolutely sure what did the trick - I obviously forgot to clear the MODx cache now and then when working on it. I tried putting back the original files into place, but it worked nevertheless...  oO

Well, this is what I did:

1) I copied the contents of the file /assets/components/tinymce/jscripts/tiny_mce/plugins/modxlink/editor_plugin.js to the file editor_plugin_src.js in the same directory.

2) I changed the contents of the file /assets/components/tinymce/jscripts/tiny_mce/plugins/modxlink/langs/de.js to

```
tinyMCE.addI18n('de.modxlink',{
    link_desc:"Link einf\u00FCgen/bearbeiten"
});
```

3) In the file /assets/components/tinymce/jscripts/tiny_mce/plugins/modxlink/langs/de_dlg.js I changed the line

```
list:"Linkliste",
```

to

```
,search:"Seite suchen"
```

and added the lines

```
,pagetitle: "Seitentitel"
,alias: "Alias"
```

I also placed the commas at the beginning of the lines as it is done in the English version of the file. Here's the complete code:

```
tinyMCE.addI18n('de.modxlink_dlg',{
title:"Link einf\u00FCgen/bearbeiten"
,url:"Adresse"
,target:"Fenster"
,titlefield:"Titel"
,is_email:"Diese Adresse scheint eine E-Mail-Adresse zu sein. M\u00F6chten Sie das dazu ben\u00F6tigte \"mailto:\" voranstellen?"
,is_external:"Diese Adresse scheint ein externer Link zu sein. M\u00F6chten Sie das dazu ben\u00F6tigte \"http://\" voranstellen?"
,search:"Seite suchen"
,general_tab:"Allgemein"
,popup_tab:"Popup"
,events_tab:"Ereignisse"
,advanced_tab:"Erweitert"
,general_props:"Allemeine Eigenschaften"
,popup_props:"Popup-Eigenschaften"
,event_props:"Ereignisse"
,advanced_props:"Erweiterte Eigenschaften"
,popup_opts:"Optionen"
,anchor_names:"Anker"
,target_same:"Im selben Fenster/Frame \u00F6ffnen"
,target_parent:"Im \u00FCbergeordneten Fenster/Frame \u00F6ffnen"
,target_top:"Im obersten Frame \u00F6ffnen (sprengt das Frameset)"
,target_blank:"In neuem Fenster \u00F6ffnen"
,popup:"JavaScript-Popup"
,popup_url:"Popup-Adresse"
,popup_name:"Name des Fensters"
,popup_return:"Link trotz Popup folgen"
,popup_scrollbars:"Scrollbalken anzeigen"
,popup_statusbar:"Statusleiste anzeigen"
,popup_toolbar:"Werkzeugleisten anzeigen"
,popup_menubar:"Browsermen\u00FC anzeigen"
,popup_location:"Adressleiste anzeigen"
,popup_resizable:"Vergr\u00F6\u00DFern des Fenster zulassen"
,popup_dependent:"Vom Elternfenster abh\u00E4ngig <br /> (nur Mozilla/Firefox) "
,popup_size:"Gr\u00F6\u00DFe"
,popup_position:"Position (X/Y)"
,id:"ID"
,style:"Format"
,classes:"Klassen"
,target_name:"Name der Zielseite"
,langdir:"Schriftrichtung"
,target_langcode:"Sprache der Zielseite"
,langcode:"Sprachcode"
,encoding:"Zeichenkodierung der Zielseite"
,mime:"MIME-Type der Zielseite"
,rel:"Beziehung der Seite zum Linkziel"
,rev:"Beziehung des Linkziels zur Seite"
,tabindex:"Tabindex"
,accesskey:"Tastenk\u00FCrzel"
,ltr:"Links nach rechts"
,rtl:"Rechts nach links"
,link_list:"Linkliste"
,pagetitle: "Seitentitel"
,alias: "Alias"
});
```

4) I cleared the MODx cache and reloaded the resource I was working on in the Manager. After that, the German translation for this plugin worked perfectly.

**Comment by MadeMyDay** [comment]
I did every single step of your description. Cleared MODx/browser cache after every step. No changes. 

@enigmatic: Could you send me (mh ät siebennull.com) your complete tinyMCE-folder or attach it in the german forums? I would try it with that.

Thx
Marc

edit: Tried it on another installation (no upgrades from previous versions), worked like a charme. So the one installation seems to be messed up somehow.

another edit: Now it works even on the problematic installation. Cache cleared, user settings reload, session flush, browser cache cleared, logged in again et voilà. No idea why.

**Comment by enigmatic-user** [comment]
@MadeMyDay: Your experiences coincide with mine when I tried to undo my changes one by one to find out what exactly caused the main problem. It still behaved as if I hadn't undone the changes. That's strange... But I'm glad it finally worked for you.

**Comment by Paprikas** [comment]
Fixed in git. in 4.1.2 rc1
Works fine with russian.
