### ISSUE TITLE
File manager for image insertion: filter, directory access limitation

### ISSUE THREAD

**Issue by speicus** [splittingred/TinyMCE#17]
Modx 2.0.4-pl
TinyMCE 4.1.1-pl

When using the file manager in image insertion dialog:
1. The first files end-user sees after file manager starts are .gitignore, .htaccess and *.php which reside in root directory. These definitely aren't images, so I guess there's some error in the filter.
2. I can't find a setting which would limit file manager to a certain branch in the directory tree. For example, I'd like to limit it to Gallery's "/assets/components/galler/files" only, because there's really no point for end-user to see MODx core files during image insertion process.

P.S. And thank you for you work, splittingred :)

**Comment by splittingred** [comment]
#1 isn't a feature yet for Revolution; #2 is filemanager_path and filemanager_url

**Comment by speicus** [comment]
N1, understood.

N2, not exactly what I meant... This would set a path for filemanager in all backend apps, while I was talking about setting a path for TinyMCE's file manager instance only. Like, only to a directory containing images. Though, I guess, my problem can be solved by changing global settings too. I'll just have to create a separate directory for user files and set Gallery to store it's files there.

Thanks for swift response.
