### ISSUE TITLE
Image-browser not loading

### ISSUE THREAD

**Issue by StevenLangbroek** [splittingred/TinyMCE#2]
I've just upgraded to RC3. Now when I want to insert an image in the content-field of a page, i click on the "Insert image" icon, then on the "Browse" icon, but then the tree in the selector is empty... Any thoughts?

**Comment by splittingred** [comment]
Unfortunately this is a core issue, it seems. So closing this, see here: http://svn.modxcms.com/jira/browse/MODX-2128

**Comment by StevenLangbroek** [comment]
Tried applying the patch, still doesn't work.. Any thoughts/help?

**Comment by goldsky** [comment]
The debug is here:
http://modxcms.com/forums/index.php/topic,53205.msg307994.html#msg307994
