### ISSUE TITLE
Error: Package not found.

### ISSUE THREAD

**Issue by eerne** [splittingred/TinyMCE#3]
When trying to install TinyMce 4.0.1-rc1 with Package Management in a freshly installed modx-2.0.0-pl, the Package installer says: "Error: Package not found." There is no js error. and currently no License Agreement, although I was pretty sure the first time there was a License Agreement, but maybe from the last package.

Other packages installed fine without any problems (Gallery, wayfinder, getresources, firstchildredirect, googlesitemap)

**Comment by snlr** [comment]
same here

**Comment by splittingred** [comment]
Try 4.0.1-rc2

**Comment by eerne** [comment]
somehow the unzipping didn't work. I tried to unzipp locally and upload: now the License appears but with it still an error package not found.

If I ignore those errors and just continue it tries to install and gives "Could not install package with signature: tinymce-4.0.1-rc2"

```
    Console running...
    PHP warning: ZipArchive::close() [ziparchive.close]: Invalid or unitialized Zip object
    Could not unpack package /home/httpd/vhosts/mydomain.ch/httpdocs/core/packages/tinymce-4.0.1-rc2.transport.zip to /home/httpd/vhosts/mydomain.ch/httpdocs/core/packages/. SIG: tinymce-4.0.1-rc2
    Attempting to install package with signature: tinymce-4.0.1-rc2
    Package found...now preparing to install.
    xPDOZip: Error opening archive at        /home/httpd/vhosts/mydomain.ch/httpdocs/core/packages/tinymce-4.0.1-rc2.transport.zip
    PHP warning: ZipArchive::extractTo() [ziparchive.extractto]: Invalid or unitialized Zip object
    Could not install package with signature: tinymce-4.0.1-rc2
```

**Comment by snlr** [comment]
I'm getting the same error (rc2) as eerne.

**Comment by eerne** [comment]
also tried to do a real "manual installation" with http://svn.modxcms.com/docs/display/revolution20/Installing+a+Package#InstallingaPackage-ManualInstallation but got the same error. Is 'Add New Package' still supported and working?

**Comment by splittingred** [comment]
Is allow_url_fopen on on your servers? Just a guess.

**Comment by splittingred** [comment]
eerne: yes, add new package works fine. This seems to be a size issue.

**Comment by splittingred** [comment]
Confirmed as actually a problem with the PHP zip extension 1.8.11; upgrading the zip extension in PHP to 1.9.1 fixes the issue.

**Comment by snlr** [comment]
I can confirm that now with PHP Zip extension 1.9.1 (server upgrade to Ubuntu 10.4), TinyMCE could be installed and works. Thanks for your help!!

**Comment by eerne** [comment]
Sorry for posting on this closed issue, but I just found out, that:

this version doesn't unzip TinyMCE:
Zip version 1.8.11 
Libzip version 0.8.0-compatible 

this version DOES unzip TinyMCE
Zip version 1.8.11 
Libzip version 0.9.0

**Comment by splittingred** [comment]
Set the 'archive_with' System Setting in MODx to Yes, or 1.
