### ISSUE TITLE
\n\r issue

### ISSUE THREAD

**Issue by BobRay** [splittingred/TinyMCE#30]
When you switch from RTE mode to HTML mode and back in TinyMCE, "\n\r" is added to the end of each paragraph. That may be normal, but the RTE display then renders the newline and the </p> tags as line breaks so the line spacing appears to double. (At least on FF 3.6.12 Vista).

To reproduce type the following in RTE mode:

line1(enter)
line2(enter)
line3(enter)

Then switch to HTML mode and back.

**Comment by splittingred** [comment]
Seems to be fixed in TinyMCE upgrade to 4.2.4; will be in next TinyMCE release.
