### ISSUE TITLE
endless saving under 2.0.5pl with TinyMCE

### ISSUE THREAD

**Issue by anselmh** [splittingred/TinyMCE#32]
After upgrading some sites to MODx 2.0.5pl (from 2.0.4pl2) the saving message doesn't disappear in one of my installations after saving content (with TinyMCE enabled, latest).

Weird that on same server with same cofig another installation doesn't hav any problems here.
Of course, it's not any caching system, browser-setting/cache.
Error log doesn't produce an error for that. And it seems to store it in some way but it doesn't arrive in frontend.

If you need to know more, please write...

**Comment by gadamiak** [comment]
I confirm that with TMCE 4.1.2 and MODx 2.0.5-pl (git). The resource gets saved but a save dialog shows forever. A page reload is required to see the changes.

**Comment by anselmh** [comment]
For me it now works fine. I completely reinstalled TinyMCE manually (because Uninstalling via Package Manager didn't work, too!), then made some tidy in my packages folder and newly installed tinyMCE.

**Comment by gadamiak** [comment]
Looks like it's browser specific. It works fine for me in FF and Safari, but loops forever in Opera.

**Comment by anselmh** [comment]
For me it was in all major browsers (with cleared cache): Saf, FF, Chrome, Opera, IE

**Comment by gadamiak** [comment]
Well, it looks to be worse: the same problem is on any page, even with `richtext` not enabled. I'm going to report it as MODx bug.

**Comment by anselmh** [comment]
Try to delete cookies from manager, empty cache, empty server cache (manually in /core/cache/), tidy up your package management and say if it's going on afterwards...

**Comment by splittingred** [comment]
Can't reproduce.

**Comment by gadamiak** [comment]
It's related to Opera only, see issue #27.

**Comment by anselmh** [comment]
I don't think it's Opera only. Think it's an caching / tmp error in filesystem. Can't reproduce for now in any browser and installation but had had it directly after upgrading to 2.0.5pl in one of my installations (not in all).

**Comment by gadamiak** [comment]
As I commented on #27, for me it happens in Opera only and _for any_ resource. After setting `which_editor` to `None` for my user (full administrator), the proper saving has restored in Opera. In Safari and FF saving works without problems. Thus I guess it's Opera only. However, I'll check if clearing the Opera cache and manager cookies helps.

**Comment by gadamiak** [comment]
Clearing caches doesn't help.

**Comment by anselmh** [comment]
Okay, it now appears again for me and it's only opera (v11).
Clearing caches and cookies doensn't help.
Maybe it's a Opera 11<->extJS problem?

**Comment by gadamiak** [comment]
I use Opera/9.80 (Windows NT 5.1; U; pl) Presto/2.6.30 Version/10.63 and the problem occurs **only with TinyMCE enabled**.

**Comment by XP1** [comment]
See this thread for a fix:
11.61 and modx revolution: infinite save loop; json error
http://my.opera.com/community/forums/topic.dml?id=1287402

I used this demo for testing:
http://www.opensourcecms.com/scripts/details.php?scriptid=48

MODX is using an [about:blank](about:blank) iframe. In Opera, this may show a "[opera:crossnetworkwarning](opera:crossnetworkwarning)":

> Warning
> 
> http://demo.opensourcecms.com/modx/manager/about:blank
> 
> A page on the public Internet requests data from your computer. For security reasons, automatic access is blocked, but you may choose to continue.
> 
> Continue
> 
> Always continue when data is requested from my computer

I think that Opera may not be the only one to block access to [about:blank](about:blank). The NoScript extension for Firefox may block [about:blank](about:blank) too: http://noscript.net/faq#qa1_9

I have created a user JS that fixes iframes in MODX to observe strict, cross-domain, same-origin policy restrictions.

Fix MODX:
https://gist.github.com/1779333/

Installing user JS:
1. Create a folder for storing user JS files.
2. Go to the user JS on GitHub > Right click on "raw" > Save Linked Content As... > Save the JS file to your user JS folder.
3. Opera > Settings > Preferences... > Advanced > Content > JavaScript Options... > Under "User JavaScript folder", select "Choose..." > Select the folder > OK > OK > OK.

Don't forget to change your includes to your MODX host.
