### ISSUE TITLE
ModxLink plugin doesn't allow input site url.

### ISSUE THREAD

**Issue by Paprikas** [splittingred/TinyMCE#34]
For example we have site: modxcms.com
If we want to create a link, we select text and click on the link button (modxlink plugin used).
Then, paste url or [[~id]].
But it won't work if you use raw http link instead of [[++site_url]]
If I paste http://modxcms.com, after saving it will be replaced with "../../undefined/"
So only placeholder works.

**Comment by splittingred** [comment]
Can't reproduce.

**Comment by Paprikas** [comment]
What is your host? What are you trying to input?

for example if i have hostname example.com
and I input http://example.com, i'll receive this bug.

PS. tested with 2.0.5 pl and latest tinymce from repo at this time.
