### ISSUE TITLE
tablecontrols Adds blank line

### ISSUE THREAD

**Issue by sirspacey** [splittingred/TinyMCE#39]
When I add the term:

tablecontrols

To the "Custom Buttons Rows 3" in the System Settings for the tinymce Area it adds a blank line, but no buttons.

**Comment by samsargent** [comment]
I had a similar issue but managed to solve it but making sure that "table" was added to the Custom Plugins setting (tiny.custom_plugins) in System Settings. 

It seems to add the row for the buttons but without the plugin loaded it doesn't add the buttons.
