### ISSUE TITLE
Unable to set TinyMCE styles via System Settings

### ISSUE THREAD

**Issue by SiNNuT** [splittingred/TinyMCE#4]
_Upon further examination it turns out the settings are under tinymce area filter so setting these should do the trick and it isn't an issue. CSS Selectors for Editor got me confused_

Not sure where to raise issues nowadays, GitHub or Jira so did both.

Using: 4.0.1-rc1
Setting the 'System Settings' -> 'CSS Selectors for Editor' value doesn't result in population of the TinyMCE Styles dropdown.

Possible solution:

Changing lines 72 and 87 in tinymce.class.php to:
    'theme_advanced_styles' => $this->modx->getOption('editor_css_selectors',null,''),

and

line 43 in tinymce.panel.js to:
    ,css_selectors: MODx.config['editor_css_selectors']

This did the trick for me but i don't know if this is the preferred way.

**Comment by enigmatic-user** [comment]
You used editor_css_selectors, but there's already a working solution with tiny.css_selectors. Maybe the line

```
'theme_advanced_styles' => $this->modx->getOption('tiny.css_selectors',$this->properties,''),
```

could be changed to

```
'theme_advanced_styles' => $this->modx->getOption('tiny.css_selectors',$this->properties,$this->modx->getOption('editor_css_selectors',$this->properties,'')),
```

so editor_css_selectors can be used as a fallback option.
