### ISSUE TITLE
TinyMCE is adding BR tags to my content after I switch from 'fullscreen' mode back to normal view.

### ISSUE THREAD

**Issue by Hlight** [splittingred/TinyMCE#46]
TinyMCE is adding BR tags to my content after I switch from 'fullscreen' mode back to normal view.  

Detailed post with description:
http://modxcms.com/forums/index.php/topic,61971.msg351988.html#msg351988

Environment:
modx: rev 2.0.8-pl, TinyMCE 4.1.2 - just upgraded to 4.2.0-pl no difference in behavior
localhost: Apache/2.0.63 (Unix) PHP/5.2.11 DAV/2, MySQL client version: 5.1.37

**Comment by splittingred** [comment]
Seems to be fixed in TinyMCE upgrade to 4.2.4; will be in next TinyMCE release.

**Comment by Hlight** [comment]
Thanks Shaun !  You rock
