### ISSUE TITLE
Templates not working on 4.2.2 / MODx 2.0.7

### ISSUE THREAD

**Issue by kenquad** [splittingred/TinyMCE#50]
Reposting from bug erroneously opened in the core tracker :-)

See forum thread at http://modxcms.com/forums/index.php/topic,62076.msg353040.html#msg353040 for details. Since one user did get it working under his test environment, perhaps it's an issue that only shows up in certain server configurations.

Linux (shared hosting), MySQL 5.1.52, PHP 5.2.15

**Comment by splittingred** [comment]
Seems to work fine for me. I'd need a lot more info, such as how you're setting it up, etc.
Also, if you have anything in the Setting "tiny.core_path", that'd be important, too.

**Comment by kenquad** [comment]
I'll get you whatever relevant info you need.

It's been awhile, so I might be forgetting something in how I set it up, but here's what I've got:
1. An html file in assets/templates/imgleft.html
2. An entry under tiny.template_list: Test:assets/templates/imgleft.html:Test

When I try to insert template content inside TinyMCE, the template dropdown is blank.

I can't find tiny.core_path using the search feature or filters - can you tell me how to bring it up?

I am using path aliases on this site, if that makes any difference (which I doubt).
