### ISSUE TITLE
paragraph tags turning into pre tags

### ISSUE THREAD

**Issue by jalz** [splittingred/TinyMCE#51]
Hi,
When I apply some bullets to a selection of text, and click on save, TinyMCE for seme reason converts all my <p> and </p> tags into <pre> and </pre> which makes the text in my bidy go all funny. Incidentally it does convert the text highlighted in bullets.

**Comment by splittingred** [comment]
Seems to be fixed in TinyMCE upgrade to 4.2.4; will be in next TinyMCE release.
