### ISSUE TITLE
missing language files

### ISSUE THREAD

**Issue by anselmh** [splittingred/TinyMCE#53]
bitbox wrote in the forums:

Hi,

I'm just starting a new MODx deployment based on the (latest) MODx 2.0.8 release.
As usual I'm installing the TinyMCE editor package that is currently available under its 4.2.1 version in the package manager.

All is fine... Until I go and insert an image into a TinyMCE managed content.
What I discover is that all labels are missing, they all show up as {#advimage_dlg.alt}, {#advimage_dlg.src} or {#advimage_dlg.title}...
The same behavior rules in all of TinyMCE's pop-up windows (plugins).

That is when I set the "manager_language" system setting to "fr", whenever I switch back to the "en" value all is fine  
I first checked that the "fr" lexicon for TineMCE was present and that was the case.
I tried uninstalling / reinstalling the package many times and nothing got better. I also double checked the MODx Error Log but nothing showed up there either

So I finally turned to my local apache logs and found out that the TinyMCE plugin's "langs" file was missing !

QUOTE
[Wed Mar 09 00:16:50 2011] [error] [client 127.0.0.1] File does not exist: /..../assets/components/tinymce/jscripts/tiny_mce/plugins/advimage/langs/fr_dlg.js, referer: http://dev.local:8888/.../assets/components/tinymce/jscripts/tiny_mce/plugins/advimage/image.htm?v=208pl

Copying the fr_dlg.js file from a previous installation into the referred directory fixed the problem   

Splittingred: may I suggest that you update the package so to include all plugins translations as it used to be, I think many people around will find it useful, thank you very much.

Oh, just another note on the fly, I think you must be using Mac OS to prepare your packages, because there are some .DS_Store files hanging around here and there in the package  
I'm often faced with the same problem myself... I personally chose to work with "Path Finder" that offers a nice alternative to the Finder and has a few other advantages like not creating the infamous .DS_Store files and letting you see (dot) .named files, "BlueHarvest" is yet another alternative...

Anyways, thank you for all the tremendous work you do for the MODx community, we all deeply appreciate it !

Best regards.

http://modxcms.com/forums/index.php/topic,62032.0/topicseen.html

This is true. Only en-file is delivered.

**Comment by Mark-H** [comment]
Dutch is also missing.
