### ISSUE TITLE
tinyMCE having trouble with custom filemanager_path setting REOPEN

### ISSUE THREAD

**Issue by krisj** [splittingred/TinyMCE#58]
Havign trouble getting images to show up when using a custom filemanager_path.
Images are showing fine in filemanager when accessing from the tree.
They also show fine when opening the filemanager popup via advimage plugin from tinyMCE.
when i select an image it doesnt show in the advimage plugin preview and not showing in tinymce editor window.

I tried to manually hack the tinymce.class.php by adding the path manually ... eg. line 175 add:

$baseUrl='/assets/files/';

and i can get the tinymce editor to show the image, but in the source it is still without the correct path.

not as straight forward as I thought..

**Comment by Mark-H** [comment]
If you look at the actual path being outputted (with the original code) - what is wrong? Is it missing something, or what else is wrong?

I have this working on one of mine install, tho it needed some tweaking with some base paths.

**Comment by krisj** [comment]
I think I have it working now. Took a while to get there though :) will double check and close this if I dont find any more issues

**Comment by splittingred** [comment]
This is working as expected in 2.1.0 and TinyMCE 4.2.3.

**Comment by krisj** [comment]
yep, confirmed - all good. I think it was a mixture of 2.0.7 and me still learning the ropes. thanks for your input though
