### ISSUE TITLE
TinyMCE for Rich Text TVs drops content

### ISSUE THREAD

**Issue by Northie** [splittingred/TinyMCE#59]
I've seen this on a range of sites using MODx 2.0.4 - 2.0.6 and TincyMCE 4+ (currently 4.2.3)
And in browsers FF 3.6, Chrome 9 & 10, IE 8

When specifying that a TV should be rich text the tinyMCE editir is used

Problem:

When editing a resource rich text TVs appear blank and when the document is saved, the value of the TV is updated to also being blank.

Having a quick look at the ajax requests using firebug I can see that the original content is being returned by the server - but there's a bug somewhere that stops it from being put into the textarea for rich text editing

**Comment by splittingred** [comment]
You need to update Revo to at least 2.0.8.

I can confirm this does not occur in 2.1.0.
