### ISSUE TITLE
JavaScript error when Saving a New Resources with TinyMCE 4.0.3-rc1. Editing existing Resources still works, however.

### ISSUE THREAD

**Issue by pixelchutes** [splittingred/TinyMCE#6]
Upon upgrading to TinyMCE 4.0.3-rc1, I can no longer Add New Resources with TinyMCE plugin active. Editing existing resources seems to be working fine, however.

```
Error: g.cb is undefined
Source File: /assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js
Line: 1 
```

**Comment by splittingred** [comment]
What's your Browser/OS?

**Comment by splittingred** [comment]
Also, can you clear your browser cache?

**Comment by pixelchutes** [comment]
I am running FireFox 3.6.8 / Mac OS X 10.5.8... I will try again with a fresh install, cleaned cache.

**Comment by pixelchutes** [comment]
:( No go... (running MODx 2.0.0-pl) ... even tried testing in a fresh instance of Google Chrome (v5.0.375.126)

**Comment by splittingred** [comment]
I can't duplicate this. Can you provide environment details: mysql/php/server versions, is mod_security on, magic_quotes_gpc, safe_mode, any errors in core/cache/logs/error.log, anything else i should know, etc.

**Comment by pixelchutes** [comment]
FireFox 3.6.8 / Mac OS X 10.5.8: (XAMPP) Apache/2.2.12 (Unix) DAV/2 mod_ssl/2.2.12 OpenSSL/0.9.8k PHP/5.3.0, mod_security = off, magic_quotes_gpc = off, safe_mode = off, error.log = empty ... Keep getting the same error in "assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js" preventing me from Creating a New Resource. I even force-removed every TinyMCE package before re-installing 4.0.3-rc1 and have tested with cleared browser cache as well as fresh, separate browser...both with same results.

**Comment by kozie** [comment]
It seems this problem is fixed by changing from the minimal version of the tiny_mce.js to the normal one (tiny_mce_src.js.. right?)

**Comment by splittingred** [comment]
4.0.3-rc2 adds an option to toggle using the _src library. closing.
