### ISSUE TITLE
Removing "advlink" in MODX's System Settings doesn't change a thing

### ISSUE THREAD

**Issue by Martijn1981** [splittingred/TinyMCE#61]
I would like to remove the extra tabs in the popup Link window of TinyMCE. I've tried doing this by removing "advlink" in the Custom Plugins field of the "General" area of TinyMCE's System Settings. But it doesn't change a thing.

Has it got something to do with the modxlink plugin?

**Comment by Mark-H** [comment]
modxlink is a modification to advlink (adds the resource search field). 

It should be calling modxlink, tho I seem to recall it using advlink with right click or something similar.

Could copy it, and modify it to fit your goal :)

**Comment by Martijn1981** [comment]
Thanks!

**Comment by Martijn1981** [comment]
Just wondering why this issue has now been closed. Is it fixed in the latest build?
