### ISSUE TITLE
image popup: broken file browser

### ISSUE THREAD

**Issue by gerritvanaaken** [splittingred/TinyMCE#65]
Relates to Version 4.3.0 rc1:

If you want to choose an image, and use the "search" button to launch the modx file browser, the browser looks alright at the first moment. But if you try to open and view a sub-directory of images, the browser fails and doesn’t show you anything. Only the images on the top level file branch are visible.

This is not permission-related, as it occurs even with admin permissions!

**Comment by rtripault** [comment]
I (and some French users too) are experiencing the same issue, as stated in this forum thread : http://modxcms.com/forums/index.php/topic,65549.msg370805.html#msg370805 (in French, but there is a screenshot of the JSON value returned)

**Comment by lowcraft** [comment]
File browser broken to me, but not the file manager to the left.
version of modx : 2.1.1-pl.
Same comment as above (@MeltingMedia).

**Comment by rtripault** [comment]
Hm, it seems it's been fixed in 2.1.2-dev with this commit https://github.com/modxcms/revolution/commit/c4719059512371f22aea7e4e1d8b9a823f0cad78
(so that's mostly not a TinyMCE issue)

**Comment by lowcraft** [comment]
Following these mod, work perfectly, but as @MeltingMedia says, do not use the minified js in the back office.

**Comment by splittingred** [comment]
Yes, this is a Revo 2.1.1 issue; the commit referenced by romain fixes it.

**Comment by prasno** [comment]
Hey,
im using revo 2.1.1 and tinymce 4.3.0 (german), and changed the files, but i sill can´t get the filebrowser to load the content of my folders. The stange thing is, that i know that i did work on me once in a previous installation.

///ahh found it: http://modxcms.com/forums/index.php/topic,63523.20.html
