### ISSUE TITLE
Simple layout instead of advanced for content field

### ISSUE THREAD

**Issue by gadamiak** [splittingred/TinyMCE#66]
After upgrading Revolution to 897c80b TinyMCE 4.3.0-rc1 switched from advanced to simple layout in content field (ie. a simple one-row bar on bottom). What's more, custom styles are not respected. I checked this in Opera 11 and Firefox 5. No settings for TinyMCE have been changed.

**Comment by mkschell** [comment]
I experienced this just yesterday and thought I was going mad! Thanks for the report.

**Comment by splittingred** [comment]
Should be fixed now; will release a new version after i fix some other bugs. Look for 4.3.0-rc2.

**Comment by gadamiak** [comment]
Great!

**Comment by gadamiak** [comment]
I confirm it's been fixed. Thank you.
