### ISSUE TITLE
No fallback if language files are missing

### ISSUE THREAD

**Issue by frippz** [splittingred/TinyMCE#69]
I discovered this by chance when I switched manager language to "sv" and then clicked on the image toolbar icon in TinyMCE. In this case it was the plugin advimage that was lacking the proper lang file. While I can appreciate the fact that no one made a translation for a particular language, there should be a fallback in place that reverts to english for example.

Additional: I took a look at http://tinymce.moxiecode.com/i18n/index.php?ctrl=lang&act=download&pr_id=1 and noticed that the swedish translation is indeed incomplete.

Maybe a fallback function is something that should be addressed directly in TinyMCE, and not the MODx plugin? I noticed there actually has been a bug filed back in 2009 in their own bug tracker (http://tinymce.moxiecode.com/develop/bugtracker_view.php?id=3846).

**Comment by Mark-H** [comment]
I too think this is something that needs to be fixed in TinyMCE (the moxiecode one). Just spent some time trying to figure out where the langs are loaded to see if I could submit a fix but don't quite understand where it's getting it from yet.
