### ISSUE TITLE
2 TinyMCE's, first ishidden, second one wrong

### ISSUE THREAD

**Issue by kozie** [splittingred/TinyMCE#7]
Hi,

Im using Revo 2.0.0-pl and the tinymce packace 4.0.2-pl in Firefox 3.6.8 (Win7 pro 64bit).
I have added a TV (rte) but it seems i can't edit it. Everything i change in it won't save.

With Firebug you can see 2 span's for TinyMCe where the first one is hidden (display:none) and the second one is the visible TinyMCE.

If i remove the style 'display:none' from the first TinyMCE span, do my changes in the first TinyMCE (the 'hidden one') and then save.. everything goes fine.

My guess is that there's one script that will make all textarea's into tinymce and another script which applies tinymce per textarea.. meaning some textarea's get tinymce'd twice.

Maybe the following illustation makes sense..
http://www.imagedump.nl/img291/3872/36tinymce.jpg

**Comment by wshawn** [comment]
It appears that both instances are named the same: id="tv_2parent" which is not allowed for javascript to function correctly.  JS libraries will simply grab the first one -- which is probably the case in this one.  It is looking for input in the hidden one.

**Comment by splittingred** [comment]
Can't replicate this at all. Closing.

**Comment by splittingred** [comment]
Fixed in 4.0.3-pl
