### ISSUE TITLE
'cirkuit' skin lacks stubs for flash / video content

### ISSUE THREAD

**Issue by drscre** [splittingred/TinyMCE#70]
When flash object is added in TinyMCE editor it is displayed just like a transparent square.

In the default in o2k7 theme there is a special css class in content.css for such cases:

<pre>
.mceItemMedia {border:1px dotted #cc0000; background-position:center; background-repeat:no-repeat; background-color:#ffffcc}
.mceItemShockWave {background-image:url(../../img/shockwave.gif)}
.mceItemFlash {background-image:url(../../img/flash.gif)}
.mceItemQuickTime {background-image:url(../../img/quicktime.gif)}
.mceItemWindowsMedia {background-image:url(../../img/windowsmedia.gif)}
.mceItemRealMedia {background-image:url(../../img/realmedia.gif)}
.mceItemVideo {background-image:url(../../img/video.gif)}
.mceItemIframe {background-image:url(../../img/iframe.gif)}
.mcePageBreak {display:block;border:0;width:100%;height:12px;border-top:1px dotted #ccc;margin-top:15px;background:#fff url(../../img/pagebreak.gif) no-repeat center top;}
</pre>

It would be greate to add similar classes to cirkuit content.css

**Comment by Mark-H** [comment]
Is this something only going on in this TinyMCE Extra for MODX - or something that is present (or rather missing) in the main TinyMCE as well?

**Comment by drscre** [comment]
This is a minor issue with a 'cirkuit' skin which is a part of TinyMCE Extra for MODX.

Original TinyMCE doesn't have this skin.

**Comment by Mark-H** [comment]
Okay - it would probably be best to inform the developer of the Cirkuit plugin as well: http://www.cirkuit.net/projects/tinymce/cirkuitSkin/#feedback

Suppose a Tiny fix wouldn't hurt though - when you manually add the code you mention above to the file you mention, does that fix the issues you're having? If so... you got the report, and the solution, so you could of course help Shaun (the main developer on this addon, as well as dozens of other addons) out, and provide him with the solution so he can just validate & integrate it when he finds time :)
