### ISSUE TITLE
modal option for file browser window

### ISSUE THREAD

**Issue by lukemcd** [splittingred/TinyMCE#77]
Clicking on the Add Image or Insert Media button when using TinyMCE opens a new window. Clicking the browse button opens yet another window. These windows appear as separate full screen tabs on tablet browsers and browsers in full-screen mode (as promoted by OS X Lion). These browsing methods are most likely going to become more and more common. The user experience would be much better with modal windows instead of new tabs popping open.

I found that there is a TinyMCE option "dialog_type" that defaults to "window" but can be set to "modal". I can't tell if this applies to the media browser. If so it would be nice to have this option.

http://www.tinymce.com/wiki.php/Configuration:dialog_type

**Comment by splittingred** [comment]
That method only works for IE; hence why it's not implemented.
