### ISSUE TITLE
Won't save when editing a Rich Text TV

### ISSUE THREAD

**Issue by damonbauer** [splittingred/TinyMCE#8]
I can't get TinyMCE to save content in a rich text TV.  I can see in the recent documents that the page is being updated, but the content isn't saved. Changing the TV from Rich Text to Textarea works as expected.

I'm using Revolution 2.0.0-pl rev7212, TinyMCE 4.0.3-rc2.  Windows Server 2008 w/ FastCGI, MySQL 5.l.49.  Tested in Firefox, IE 8, Safari and Chrome, none work.

Firebug tells me this when trying to save the page:

B is null
http://...../manager/assets/ext3/ext-all.js
Line 7

**Comment by splittingred** [comment]
Fixed in 4.0.3-pl
