### ISSUE TITLE
problem with languages

### ISSUE THREAD

**Issue by alextv** [splittingred/TinyMCE#9]
tinymce-4.0.4-rc2.transport.zip
modx-2.0.0-pl.zip

1)if change language in plug-in parameters to any different from 'en' then editor disappears. In this case compressed version of tiny_mce.js is used.
I found that editor try to load assets\components\tinymce\jscripts\tiny_mce\plugins\modxlink\langs[language].js file which is missing.
2) if use not compressed tiny_mce.js library then editor available but advlink plug-in(button) disappears from editor.

Hope this helps

**Comment by splittingred** [comment]
Fixed in git
